Updated filenames + settings

diff --git a/workgroup4/co_expr_qtl/Snakefile b/workgroup4/co_expr_qtl/Snakefile
--- a/workgroup4/co_expr_qtl/Snakefile
+++ b/workgroup4/co_expr_qtl/Snakefile
@@ -65,15 +65,14 @@ def get_batch_number(wildcards):
 
 rule all:
   input: 
-    merged_coeqtls = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects-allsignificantTriplets.txt", cell_type=config["settings"]["cell_type"])
-    # merged_coeqtls = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects.txt", cell_type=config["settings"]["cell_type"])
+    merged_coeqtls = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-AllEffects-allsignificantTriplets.txt", cell_type=config["settings"]["cell_type"])
 
 rule create_linkfile:
   input: 
     corr = config["inputs"]["co_expr_dir"] + "correlations/data/{cell_type}/chr{chr}/{cell_type}.chr.{chr}.corr.transpose.stripped.txt.gz",
     wg0 = config["inputs"]["wg0_file_directories"]
   output: 
-    linkfile = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/linkfile.txt"
+    linkfile = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/linkfile.txt",
   resources:
     mem_per_thread_gb = lambda wildcards, attempt: attempt * config["create_linkfile_memory"],
     disk_per_thread_gb = lambda wildcards, attempt: attempt * config["create_linkfile_memory"],
@@ -109,7 +108,10 @@ rule create_snp_gene_pair_triplet:
     bind = config["inputs"]["bind_path"],
     sif = config["inputs"]["singularity_image"],
     script =  config["inputs"]["repo_dir"] + "scripts/get_snp_genepair_triplets.py",
-    signif_column = config["settings"]["signif_column"],
+    significance_col = config["settings"]["signif_column"],
+    chr_col = config["settings"]["chr_column"],
+    gene_col = config["settings"]["gene_column"],
+    snp_col = config["settings"]["snp_column"],
     alpha = config["settings"]["alpha"],
     out = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/"
   log: config["outputs"]["output_dir"] + "log/{cell_type}/chr{chr}/create_snp_gene_pair_triplet.{cell_type}.chr.{chr}.log"
@@ -117,9 +119,12 @@ rule create_snp_gene_pair_triplet:
     """
     singularity exec --bind {params.bind} {params.sif} python {params.script} \
       --chr {wildcards.chr} \
-      --top_effects {input.top_effects} \
       --corr {input.corr} \
-      --signif_column {params.signif_column} \
+      --top_effects {input.top_effects} \
+      --chr_col {params.chr_col} \
+      --significance_col {params.significance_col} \
+      --gene_col {params.gene_col} \
+      --snp_col {params.snp_col} \
       --alpha {params.alpha} \
       --out {params.out} > {log} 2>&1
     """
@@ -273,7 +278,8 @@ rule run_co_eqtl:
 rule merge_batches:
   input:
     done = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/batches/chr{chr}-batches.done",
-    coeqtls = lambda wildcards: expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/output/chr{chr}-batch-{n_batch}-TopEffects.txt", n_batch=get_batch_number(wildcards), allow_missing=True)
+    coeqtls = lambda wildcards: expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/output/chr{chr}-batch-{n_batch}-TopEffects.txt", n_batch=get_batch_number(wildcards), allow_missing=True),
+    finished = lambda wildcards: expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/output/chr{chr}-batch-{n_batch}-TopEffects.finished", n_batch=get_batch_number(wildcards), allow_missing=True)
   output:
     merged_batches = temp(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/{cell_type}-chr{chr}-TopEffects.txt")
   resources:
@@ -319,7 +325,7 @@ rule multiple_testing_correction:
   input:
     coeqtls = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects.txt"
   output:
-    effects = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffect-multiple_testing_correction.txt",
+    effects = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects_multiple_testing_correction.txt",
     hist = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/plots/{cell_type}-TopEffects_hist.png",
     overview = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/plots/{cell_type}-TopEffects_overview.png"
   resources:
@@ -334,7 +340,6 @@ rule multiple_testing_correction:
     alpha = config["mbqtl_settings"]["alpha"],
     out = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects",
     plot_out = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/plots/{cell_type}-TopEffects"
-    prefix = "-multiple_testing_correction"
   log: config["outputs"]["output_dir"] + "log/{cell_type}/multiple_testing_correction.{cell_type}.log"
   shell:
     """
@@ -353,18 +358,18 @@ rule multiple_testing_correction:
       --alpha {params.alpha} \
       --data_out {params.out} \
       --plot_out {params.plot_out} \
-      --suffix {params.prefix} > {log} 2>&1
+      --suffix '_multiple_testing_correction' > {log} 2>&1
     """
 
 rule get_significant_effects:
   input:
-    coeqtl = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffect-multiple_testing_correction.txt",
+    coeqtl = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects_multiple_testing_correction.txt",
     # batches = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}/batches/chr{chr}-batches.done", chr=config["settings"]["chromosomes"], allow_missing=True),
     triplet = expand(config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/snp_genepair_triplets_to_test.txt", chr=config["settings"]["chromosomes"], allow_missing=True)
   output:
-    significant_effects = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/EX-TopEffects-significant.txt",
-    genepairs = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/genepairs_to_dump.txt",
-    snp_genepairs = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/snp_genepairs_to_dump.txt"
+    significant_effects = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects-significant.txt",
+    genepairs = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-genepairs_to_dump.txt",
+    snp_genepairs = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-snp_genepairs_to_dump.txt"
   resources:
     mem_per_thread_gb = lambda wildcards, attempt: attempt * config["get_significant_effects_memory"],
     disk_per_thread_gb = lambda wildcards, attempt: attempt * config["get_significant_effects_memory"],
@@ -375,7 +380,7 @@ rule get_significant_effects:
     sif = config["inputs"]["singularity_image"],
     script = config["inputs"]["repo_dir"] + "scripts/get_significant_effects.py",
     signif_column = config["settings"]["signif_column"],
-    out = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/",
+    out = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}",
     batches = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/"
   log: config["outputs"]["output_dir"] + "log/{cell_type}/get_significant_effects.{cell_type}.log"
   shell:
@@ -383,7 +388,7 @@ rule get_significant_effects:
     singularity exec --bind {params.bind} {params.sif} python {params.script} \
       --input {input.coeqtl} \
       --out {params.out} \
-      --signif_column {params.signif_column}
+      --signif_column {params.signif_column} \
       --batches {params.batches} \
       --snp_genepair_triplets {input.triplet} > {log} 2>&1
     """
@@ -394,14 +399,14 @@ rule run_coeqtl_dump:
     correlation = config["inputs"]["co_expr_dir"] + "correlations/data/{cell_type}/chr{chr}/{cell_type}.chr.{chr}.corr.transpose.stripped.txt.gz",
     linkfile = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/linkfile.txt",
     filtered_genotype = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/{cell_type}.eqtlsnps.bgz.vcf.gz",
-    gene_pairs = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/genepairs_to_dump.txt",
+    gene_pairs = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-genepairs_to_dump.txt",
     triplet_group = config["outputs"]["output_dir"] + "coeQTL/reffiles/{cell_type}/chr{chr}/genepair_egene_groups.txt",
-    triplet = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/snp_genepairs_to_dump.txt"
+    triplet = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-snp_genepairs_to_dump.txt"
   output:
     # log = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/dump/chr{chr}-dump-log.txt.gz",
     # finished = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/dump/chr{chr}-dump-TopEffects.finished",
     # coeqtls = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/dump/chr{chr}-dump-TopEffects.txt"
-    done = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/dump/chr{chr}-dump-TopEffects.done"
+    done = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/log/chr{chr}-dump-TopEffects.done"
   resources:
     java_mem_gb = lambda wildcards, attempt: attempt * config["run_coeqtl_dump_memory"] * config["run_coeqtl_dump_threads"] - config["settings_extra"]["java_memory_buffer"],
     mem_per_thread_gb = lambda wildcards, attempt: attempt * config["run_coeqtl_dump_memory"],
@@ -419,11 +424,10 @@ rule run_coeqtl_dump:
     hwep = config["mbqtl_settings"]["hwep"],
     minobservations = config["mbqtl_settings"]["minobservations"],
     mingenotypecount = config["mbqtl_settings"]["mingenotypecount"],
-    out = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/dump/chr{chr}-dump"
+    out = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/chr{chr}-dump"
   log: config["outputs"]["output_dir"] + "log/{cell_type}/chr{chr}/run_coeqtl_dump.{cell_type}.chr{chr}.log"
   shell:
     """
-    mkdir -p $(dirname {params.out})
     singularity exec --bind {params.bind} {params.sif} java -Xmx{resources.java_mem_gb}g -Xms{resources.java_mem_gb}g \
       -Djava.util.concurrent.ForkJoinPool.common.parallelism={params.java_threads} \
       -Dmaximum.threads={params.java_threads} -Dthread.pool.size={params.java_threads} \
@@ -445,17 +449,16 @@ rule run_coeqtl_dump:
       --mingenotypecount {params.mingenotypecount} \
       --fisherzmeta \
       --outputall \
-      --snpgenelimit {input.triplet} > {log} 2>&1
+      --snpgenelimit {input.triplet} > {log} 2>&1 || true
     singularity exec --bind {params.bind} {params.sif} touch {output.done}
     """
 
 rule merge_all_triplets:
   input: 
-    top_effects = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects-significant.txt",
-    done = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/dump/chr{chr}-dump-TopEffects.done", chr=config["settings"]["chromosomes"], allow_missing=True)
-    # coeqtls = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/dump/chr{chr}-dump-TopEffects.txt", chr=config["settings"]["chromosomes"], allow_missing=True)
+    significant_effects = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects-significant.txt",
+    done = expand(config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/log/chr{chr}-dump-TopEffects.done", chr=config["settings"]["chromosomes"], allow_missing=True)
   output: 
-    merged = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-TopEffects-allsignificantTriplets.txt"
+    merged = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/{cell_type}-AllEffects-allsignificantTriplets.txt"
   resources:
     mem_per_thread_gb = lambda wildcards, attempt: attempt * config["merge_all_triplets_memory"],
     disk_per_thread_gb = lambda wildcards, attempt: attempt * config["merge_all_triplets_memory"],
@@ -465,16 +468,14 @@ rule merge_all_triplets:
     bind = config["inputs"]["bind_path"],
     sif = config["inputs"]["singularity_image"],
     script = config["inputs"]["repo_dir"] + "scripts/filter_significant_triplets.py",
-    signif_column = config["settings"]["signif_column_dump"],
-    egene_column = config["settings"]["egene_column"],
-    indir = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/dump/"
+    indir = config["outputs"]["output_dir"] + "coeQTL/output/{cell_type}/"
   log: config["outputs"]["output_dir"] + "log/{cell_type}/merge_all_triplets.{cell_type}.log"
   shell:
     """
     singularity exec --bind {params.bind} {params.sif} python {params.script} \
-      --significant_egenes {input.top_effects} \
-      --signif_column {params.signif_column} \
-      --egene_column {params.egene_column} \
+      --significant_egenes {input.significant_effects} \
+      --signif_column PvalueNominalThreshold \
+      --egene_column Group \
       --indir {params.indir} \
       --output {output.merged} > {log} 2>&1
     """
